Consider the below code to answer further questions:

In [30]:
import numpy as np

variable_list = ['1','2','3','4','5' ]

array_list = np.array(object = list_)


Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code 
to print the data types of both the variables.

Ans: The Numpy array, formally called ndarray in Numpy documentation id similar to a list but where all the elements of the list are of the same type. The elements of a Numpy array, or simply an array, are usually numbers, but can also be boolians, strings or other objects.

In [10]:
type(variable_list)

list

In [11]:
type(array_list)

numpy.ndarray

Q2. Write a code to print the data type of each and every element of both the variables list_ and 
arra_list.

In [13]:
type(variable_list)

list

In [14]:
type(array_list)

numpy.ndarray

In [19]:
# variable_list:
for i in variable_list:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [27]:
# array_list:
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list.

In [33]:
array_list = np.array(object = variable_list, dtype = int)

In [34]:
#variable_list:
for i in variable_list:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [35]:
# array_list:
for i in array_list:
    print(type(i))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


Yes, the elements of variable_list are of the type 'String' and the elements of array_list are of the type 'Int'.

Consider the below code to answer further questions:

In [38]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:

(i)	 shape

(ii) size

In [39]:
# (i)
num_array.shape

(2, 3)

In [40]:
num_array.size

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [41]:
import numpy as np

In [50]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
# Arrays containing zeroes only
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [55]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])